plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

base {
    archivesName = "${archives_base_name}-${minecraft_version}-${mod_version}"
}

repositories {
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "sillys-auto-totem" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

    runConfigs.all {
        ideConfigGenerated true // Run configurations are not created for subprojects by default
        runDir "../../run" // Use a shared run folder and create separate worlds
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${property('yarn_mappings')}:v2"
    modImplementation "net.fabricmc:fabric-loader:${property('fabric_loader')}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${property('fabric_version')}"

    modImplementation include ("maven.modrinth:midnightlib:${property('midnightlib_version')}")
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

remapJar {
    destinationDirectory.set(file("$rootDir/jars"))
}

processResources {
    inputs.property "version", mod_version
    inputs.property "minecraft_version", minecraft_version
    inputs.property "loader_version", fabric_loader

    filesMatching("fabric.mod.json") {
        expand(
                "version": mod_version,
                "minecraft_version": minecraft_version,
                "loader_version": fabric_loader
        )
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
    }
}