plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

base {
    archivesName = "${project.archives_base_name}-${stonecutter.current.version}-${mod_version}"
}

repositories {
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "sillys-auto-totem" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

    runConfigs.all {
        ideConfigGenerated true // Run configurations are not created for subprojects by default
        runDir "../../run" // Use a shared run folder and create separate worlds
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${stonecutter.current.project}"
    mappings "net.fabricmc:yarn:${property('deps.yarn_mappings')}:v2"
    modImplementation "net.fabricmc:fabric-loader:${property('deps.fabric_loader')}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${property('deps.fabric_api')}"

    modImplementation include ("maven.modrinth:midnightlib:${property('midnightlib_version')}")
}

processResources {
    inputs.property "minecraft", stonecutter.current.version

    filesMatching("fabric.mod.json") {
        expand "minecraft": stonecutter.current.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()

    def java = stonecutter.eval(stonecutter.current.version, ">=1.20.5")
            ? JavaVersion.VERSION_21 : JavaVersion.VERSION_17
    targetCompatibility = java
    sourceCompatibility = java
}

jar {
    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }
}

remapJar {
    destinationDirectory.set(file("$rootDir/jars"))
    inputs.property "archivesName", project.base.archivesName
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
    }
}